### PR TITLE
Fix the link to website

### PR DESCRIPTION
**Pull request by yfer**

### CODE REVIEW

**Comment by sschmidTU** [comment]
@yfer why do you think this is relevant? I think every modern browser automatically uses https when it's available.

**Comment by yfer** [comment]
@sschmidTU 
It's not about browser, it's about the link format in Markdown. 
You can see generated link on https://opensheetmusicdisplay.github.io/ to see what is wrong.

**Comment by sschmidTU** [comment]
Oh, i see, sorry, should have tested that. Thanks!

**Comment by sschmidTU** [comment]
@yfer by the way, this github.io website is outdated anyways and opensheetmusicdisplay.org is basically the replacement, we only really use the github.io site for hosting the public OSMD demo now.

**Pull request merged**
